//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoDA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Compra> CompraSet { get; set; }
        public virtual DbSet<DetalheCompra> DetalheCompraSet { get; set; }
        public virtual DbSet<Produto> ProdutoSet { get; set; }
        public virtual DbSet<TipoProduto> TipoProdutoSet { get; set; }
        public virtual DbSet<Pessoa> PessoaSet { get; set; }
        public virtual DbSet<Colaboracao> ColaboracaoSet { get; set; }
        public virtual DbSet<Evento> EventoSet { get; set; }
        public virtual DbSet<Participacao> ParticipacaoSet { get; set; }
        public virtual DbSet<Escola> EscolaSet { get; set; }
        public virtual DbSet<Inscricao> InscricaoSet { get; set; }
    }
}
